included:
  - Gymmy

excluded:
  - Gymmy.xcodeproj

line_length:
  warning: 160
  error: 250
  ignores_comments: true
  ignores_urls: true

cyclomatic_complexity:
  warning: 20
  error: 50

function_body_length:
  warning: 100
  error: 250

type_body_length:
  warning: 350
  error: 600

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k

trailing_comma:
  mandatory_comma: false

reporter: "xcode"
